In [1]:
# input
import pandas as pd
import argparse
import numpy as np

In [2]:
def get_peaks(data,bin_size_kb=2, comp_flanksize_kb=50, fold_thresh=5):
    scaff_l = list(set(data.Scaffold))
    peak = []
    nopeak = []
    
    for scaff in scaff_l:
        onekbfile = data.loc[data.Scaffold==scaff].reset_index()
        
        for i, bin in onekbfile.iterrows():
            #print(i)
            #print(scaff)
            #print(bin.Start_bp)
            #print(onekbfile)
            #print(onekbfile.iloc[i:i+bin_size_kb-1])
            peak_mean_rho = onekbfile.iloc[i:i+bin_size_kb-1].Rho_kb.mean()
            #print(peak_mean_rho)

            if i == onekbfile.index.max():
                peak_end = onekbfile.iloc[i,].End_bp
            else:
                try:
                    peak_end = onekbfile.iloc[i+1,].End_bp
                except IndexError:
                    #print(onekbfile.index.max())
                    #print(i)
                    #print(bin)
                    peak_end = onekbfile.iloc[i,].End_bp
                    raise IndexError
                    
                    
            flank_start = i-50
            if flank_start<0: # make sure we dont overshoot the scaffold boundary
                flank_start=0
    
            flank_stop = i+bin_size_kb-1+50
            if flank_stop>onekbfile.index.max(): # make sure we dont overshoot the scaffold boundary
                flank_stop=onekbfile.index.max()

            flank_mean_rho = onekbfile.iloc[flank_start:flank_stop].Rho_kb.mean()
            #print(scaff)
            #print(bin.Start_bp)
            #print(peak_end)
            #print(peak_mean_rho)
            #print(flank_mean_rho)
            #print(peak_mean_rho/flank_mean_rho)
            fold_diff = (peak_mean_rho/flank_mean_rho)
            if fold_diff>fold_thresh:
                #print("PEAK")
                peak.append([scaff, bin.Start_bp, peak_end, True, fold_diff, peak_mean_rho, flank_mean_rho])
            else:
                nopeak.append([scaff, bin.Start_bp, peak_end, True, fold_diff, peak_mean_rho, flank_mean_rho])
        #    else: 
        #        peak.append('False')
    return peak, nopeak

In [3]:
data = pd.read_csv("../data/concat_Csec_geq1000_rmind_hardfilt_exhet_biall_dp_qfilt_mac2_maxmiss06_phimp_LDhat_bpen1_statres_filtMQ70depth2stdev.txt_w1kb", sep='\t')

In [4]:
p, pn = get_peaks(data=data)

In [5]:
peaks = pd.DataFrame(p)

In [6]:
nopeaks = pd.DataFrame(pn)

In [7]:
peaks.columns = ["scaffold", "bin_Start_bp", "bin_Stop_bp", "peak", "fold_diff", "peak_mean_rho", "flank_mean_rho"]
nopeaks.columns = ["scaffold", "bin_Start_bp", "bin_Stop_bp", "peak", "fold_diff", "peak_mean_rho", "flank_mean_rho"]

In [8]:
peaks.bin_Start_bp = peaks.bin_Start_bp.astype(int).astype(str)
peaks.bin_Stop_bp = peaks.bin_Stop_bp.astype(int).astype(str)

In [9]:
nopeaks.bin_Start_bp = nopeaks.bin_Start_bp.astype(int).astype(str)
nopeaks.bin_Stop_bp = nopeaks.bin_Stop_bp.astype(int).astype(str)

In [10]:
peaks.to_csv('../data/20231204_Csec_5fold_peaks.bed', sep='\t', header=None, index=None)

In [15]:
nopeaks.to_csv('../data/20231205_Csec_5fold_nopeaks_all.tsv', sep='\t', header=True, index=None)

In [11]:
take_idx = np.random.choice( a= range(nopeaks.index.max()), size=peaks.shape[0], replace=False )

In [12]:
nopeaks_ss = nopeaks.iloc[take_idx]

In [175]:
nopeaks_ss[["scaffold", "bin_Start_bp",	"bin_Stop_bp"]].to_csv('../data/20231205_Csec_5fold_nopeaks.bed', sep='\t', header=None, index=None)

In [236]:
peaks.shape

(40894, 7)

# make subset for testing

In [179]:
peaks.sort_values(by='fold_diff', ascending=False)

,scaffold,bin_Start_bp,bin_Stop_bp,peak,fold_diff,peak_mean_rho,flank_mean_rho
460,NEVH01014529.1,2000,3000,True,2952.507329,11.95950,0.004051
35286,NEVH01008345.1,8000,9000,True,2395.215738,2.18982,0.000914
14751,NEVH01023493.1,1000,2000,True,345.645552,3.54024,0.010242
19432,NEVH01010544.1,1000,2000,True,278.568459,8.57651,0.030788
24332,NEVH01015377.1,2000,3000,True,197.058996,1.58183,0.008027
...,...,...,...,...,...,...,...
31945,NEVH01004401.1,1014000,1016000,True,5.000310,16.80200,3.360192
5241,NEVH01006739.1,128000,130000,True,5.000204,17.61630,3.523117
23464,NEVH01026110.1,393000,395000,True,5.000201,23.96550,4.792908
5654,NEVH01002152.1,341000,343000,True,5.000108,32.76020,6.551898
19232,NEVH01003743.1,760000,762000,True,5.000008,28.98770,5.797531

In [184]:
peaks.flank_mean_rho.mean()

3.84582936180377

In [237]:
peaks_ss = peaks.loc[peaks.flank_mean_rho > 3.84582936180377].sort_values(by='fold_diff', ascending=False)

In [238]:
peaks_ss

,scaffold,bin_Start_bp,bin_Stop_bp,peak,fold_diff,peak_mean_rho,flank_mean_rho
35540,NEVH01009080.1,1613000,1615000,True,25.100482,182.4660,7.269422
33825,NEVH01026396.1,69000,71000,True,24.235714,132.0590,5.448942
15629,NEVH01024944.1,1113000,1115000,True,21.443277,84.8822,3.958453
13906,NEVH01009768.1,2173000,2175000,True,21.411040,148.0720,6.915685
37170,NEVH01021187.1,335000,337000,True,21.299898,97.7582,4.589609
...,...,...,...,...,...,...,...
34716,NEVH01009372.1,869000,871000,True,5.000585,50.8930,10.177410
4493,NEVH01018385.1,838000,840000,True,5.000467,45.5603,9.111208
23464,NEVH01026110.1,393000,395000,True,5.000201,23.9655,4.792908
5654,NEVH01002152.1,341000,343000,True,5.000108,32.7602,6.551898
19232,NEVH01003743.1,760000,762000,True,5.000008,28.9877,5.797531

In [239]:
take_idx = np.random.choice( a= range(nopeaks.index.max()), size=18473, replace=False )

In [240]:
nopeaks_ss2 = nopeaks.iloc[take_idx]

In [241]:
peaks_ss.to_csv('../data/20231204_Csec_5fold_peaks_18kss.bed', sep='\t', header=None, index=None)
nopeaks_ss2[["scaffold", "bin_Start_bp",	"bin_Stop_bp"]].to_csv('../data/20231205_Csec_5fold_nopeaks_18kss.bed', sep='\t', header=None, index=None)

In [242]:
%%bash

db=../data/Csec.fa
bed=../data/20231204_Csec_5fold_peaks_18kss.bed
out=../data/20231204_Csec_hs_5fold_18kss.fa

bedtools getfasta -fi $db -bed $bed -fo $out


db=../data/Csec.fa
bed=../data/20231205_Csec_5fold_nopeaks_18kss.bed
out=../data/20231204_Csec_hs_5fold_background_18kss.fa

bedtools getfasta -fi $db -bed $bed -fo $out

Feature (NEVH01018006.1:3000-4000) beyond the length of NEVH01018006.1 size (3609 bp).  Skipping.
Feature (NEVH01000595.1:2118000-2119000) beyond the length of NEVH01000595.1 size (2118713 bp).  Skipping.
Feature (NEVH01010480.1:2306000-2307000) beyond the length of NEVH01010480.1 size (2306319 bp).  Skipping.
Feature (NEVH01017307.1:1000-2000) beyond the length of NEVH01017307.1 size (1319 bp).  Skipping.
Feature (NEVH01014373.1:254000-256000) beyond the length of NEVH01014373.1 size (255944 bp).  Skipping.
Feature (NEVH01004982.1:58000-59000) beyond the length of NEVH01004982.1 size (58611 bp).  Skipping.
Feature (NEVH01014373.1:255000-256000) beyond the length of NEVH01014373.1 size (255944 bp).  Skipping.
Feature (NEVH01009081.1:266000-268000) beyond the length of NEVH01009081.1 size (267562 bp).  Skipping.
Feature (NEVH01013552.1:1655000-1657000) beyond the length of NEVH01013552.1 size (1656948 bp).  Skipping.
Feature (NEVH01009081.1:267000-268000) beyond the length of NEVH01009081.1 size (267562 bp).  Skipping.
Feature (NEVH01013285.1:15000-16000) beyond the length of NEVH01013285.1 size (15514 bp).  Skipping.
Feature (NEVH01008784.1:1000-2000) beyond the length of NEVH01008784.1 size (1635 bp).  Skipping.
Feature (NEVH01013552.1:1656000-1657000) beyond the length of NEVH01013552.1 size (1656948 bp).  Skipping.
Feature (NEVH01005899.1:498000-499000) beyond the length of NEVH01005899.1 size (498617 bp).  Skipping.
Feature (NEVH01004431.1:87000-89000) beyond the length of NEVH01004431.1 size (88340 bp).  Skipping.
Feature (NEVH01000250.1:2236000-2237000) beyond the length of NEVH01000250.1 size (2236795 bp).  Skipping.
Feature (NEVH01000596.1:774000-775000) beyond the length of NEVH01000596.1 size (774875 bp).  Skipping.
Feature (NEVH01010579.1:9000-10000) beyond the length of NEVH01010579.1 size (9531 bp).  Skipping.
Feature (NEVH01002561.1:46000-47000) beyond the length of NEVH01002561.1 size (46548 bp).  Skipping.
Feature (NEVH01022648.1:347000-349000) beyond the length of NEVH01022648.1 size (348327 bp).  Skipping.
Feature (NEVH01017466.1:376000-378000) beyond the length of NEVH01017466.1 size (377995 bp).  Skipping.
Feature (NEVH01017466.1:377000-378000) beyond the length of NEVH01017466.1 size (377995 bp).  Skipping.
Feature (NEVH01024947.1:574000-576000) beyond the length of NEVH01024947.1 size (575999 bp).  Skipping.
Feature (NEVH01006733.1:555000-557000) beyond the length of NEVH01006733.1 size (556343 bp).  Skipping.
Feature (NEVH01007456.1:1000-2000) beyond the length of NEVH01007456.1 size (1752 bp).  Skipping.
Feature (NEVH01016966.1:430000-432000) beyond the length of NEVH01016966.1 size (431688 bp).  Skipping.
Feature (NEVH01016967.1:465000-467000) beyond the length of NEVH01016967.1 size (466102 bp).  Skipping.
Feature (NEVH01016459.1:6000-7000) beyond the length of NEVH01016459.1 size (6493 bp).  Skipping.
Feature (NEVH01011211.1:482000-484000) beyond the length of NEVH01011211.1 size (483709 bp).  Skipping.
Feature (NEVH01021961.1:93000-94000) beyond the length of NEVH01021961.1 size (93427 bp).  Skipping.
Feature (NEVH01002992.1:1381000-1383000) beyond the length of NEVH01002992.1 size (1382781 bp).  Skipping.
Feature (NEVH01013285.1:14000-16000) beyond the length of NEVH01013285.1 size (15514 bp).  Skipping.
Feature (NEVH01025660.1:506000-508000) beyond the length of NEVH01025660.1 size (507585 bp).  Skipping.
Feature (NEVH01016966.1:431000-432000) beyond the length of NEVH01016966.1 size (431688 bp).  Skipping.
Feature (NEVH01013209.1:2000-3000) beyond the length of NEVH01013209.1 size (2298 bp).  Skipping.
Feature (NEVH01013216.1:453000-454000) beyond the length of NEVH01013216.1 size (453494 bp).  Skipping.
Feature (NEVH01004431.1:88000-89000) beyond the length of NEVH01004431.1 size (88340 bp).  Skipping.
Feature (NEVH01006733.1:556000-557000) beyond the length of NEVH01006733.1 size (556343 bp).  Skipping.
Feature (NEVH01007407.1:2413000-2415000) beyond the length of NEVH01007407.1 size (2414293 bp).  Skipping.
Feature (NEVH01002748.1:156000-157000) beyond the length of NEVH01002748.1 size (156171 bp).  Skipping.
Feature (NEVH01002992.1:1382000-1383000) beyond the length of NEVH01002992.1 size (1382781 bp).  Skipping.
Feature (NEVH01009765.1:2515000-2517000) beyond the length of NEVH01009765.1 size (2516171 bp).  Skipping.
Feature (NEVH01009418.1:333000-335000) beyond the length of NEVH01009418.1 size (334611 bp).  Skipping.
Feature (NEVH01016325.1:511000-512000) beyond the length of NEVH01016325.1 size (511803 bp).  Skipping.
Feature (NEVH01000250.1:2235000-2237000) beyond the length of NEVH01000250.1 size (2236795 bp).  Skipping.
Feature (NEVH01009765.1:2516000-2517000) beyond the length of NEVH01009765.1 size (2516171 bp).  Skipping.
Feature (NEVH01004963.1:48000-50000) beyond the length of NEVH01004963.1 size (49939 bp).  Skipping.
Feature (NEVH01004963.1:49000-50000) beyond the length of NEVH01004963.1 size (49939 bp).  Skipping.
Feature (NEVH01000612.1:279000-281000) beyond the length of NEVH01000612.1 size (280792 bp).  Skipping.
Feature (NEVH01025660.1:507000-508000) beyond the length of NEVH01025660.1 size (507585 bp).  Skipping.
Feature (NEVH01018407.1:31000-33000) beyond the length of NEVH01018407.1 size (32589 bp).  Skipping.
Feature (NEVH01009093.1:61000-62000) beyond the length of NEVH01009093.1 size (61997 bp).  Skipping.
Feature (NEVH01002685.1:303000-304000) beyond the length of NEVH01002685.1 size (303245 bp).  Skipping.
Feature (NEVH01021960.1:217000-219000) beyond the length of NEVH01021960.1 size (218478 bp).  Skipping.
Feature (NEVH01006994.1:1082000-1084000) beyond the length of NEVH01006994.1 size (1083801 bp).  Skipping.
Feature (NEVH01002685.1:302000-304000) beyond the length of NEVH01002685.1 size (303245 bp).  Skipping.
Feature (NEVH01016951.1:95000-97000) beyond the length of NEVH01016951.1 size (96901 bp).  Skipping.
Feature (NEVH01017539.1:37000-38000) beyond the length of NEVH01017539.1 size (37271 bp).  Skipping.
Feature (NEVH01018407.1:32000-33000) beyond the length of NEVH01018407.1 size (32589 bp).  Skipping.
Feature (NEVH01016951.1:96000-97000) beyond the length of NEVH01016951.1 size (96901 bp).  Skipping.
Feature (NEVH01006994.1:1083000-1084000) beyond the length of NEVH01006994.1 size (1083801 bp).  Skipping.
Feature (NEVH01005887.1:3123000-3125000) beyond the length of NEVH01005887.1 size (3124886 bp).  Skipping.
Feature (NEVH01019458.1:7000-8000) beyond the length of NEVH01019458.1 size (7402 bp).  Skipping.
Feature (NEVH01019959.1:369000-370000) beyond the length of NEVH01019959.1 size (369723 bp).  Skipping.
Feature (NEVH01002748.1:155000-157000) beyond the length of NEVH01002748.1 size (156171 bp).  Skipping.
Feature (NEVH01006765.1:518000-519000) beyond the length of NEVH01006765.1 size (518828 bp).  Skipping.
Feature (NEVH01007822.1:2978000-2980000) beyond the length of NEVH01007822.1 size (2979863 bp).  Skipping.
Feature (NEVH01026410.1:115000-116000) beyond the length of NEVH01026410.1 size (115870 bp).  Skipping.
Feature (NEVH01018372.1:1576000-1578000) beyond the length of NEVH01018372.1 size (1577270 bp).  Skipping.
Feature (NEVH01021193.1:2333000-2334000) beyond the length of NEVH01021193.1 size (2333210 bp).  Skipping.
Feature (NEVH01010480.1:2305000-2307000) beyond the length of NEVH01010480.1 size (2306319 bp).  Skipping.
Feature (NEVH01007822.1:2979000-2980000) beyond the length of NEVH01007822.1 size (2979863 bp).  Skipping.
Feature (NEVH01019395.1:290000-292000) beyond the length of NEVH01019395.1 size (291108 bp).  Skipping.
Feature (NEVH01015363.1:52000-54000) beyond the length of NEVH01015363.1 size (53351 bp).  Skipping.
Feature (NEVH01010503.1:105000-107000) beyond the length of NEVH01010503.1 size (106501 bp).  Skipping.
Feature (NEVH01015363.1:53000-54000) beyond the length of NEVH01015363.1 size (53351 bp).  Skipping.
Feature (NEVH01006619.1:136000-137000) beyond the length of NEVH01006619.1 size (136557 bp).  Skipping.
Feature (NEVH01008209.1:114000-115000) beyond the length of NEVH01008209.1 size (114327 bp).  Skipping.
Feature (NEVH01002561.1:45000-47000) beyond the length of NEVH01002561.1 size (46548 bp).  Skipping.
Feature (NEVH01010503.1:106000-107000) beyond the length of NEVH01010503.1 size (106501 bp).  Skipping.
Feature (NEVH01019395.1:291000-292000) beyond the length of NEVH01019395.1 size (291108 bp).  Skipping.
Feature (NEVH01018372.1:1577000-1578000) beyond the length of NEVH01018372.1 size (1577270 bp).  Skipping.
Feature (NEVH01024430.1:35000-36000) beyond the length of NEVH01024430.1 size (35865 bp).  Skipping.
Feature (NEVH01005222.1:2000-3000) beyond the length of NEVH01005222.1 size (2616 bp).  Skipping.
Feature (NEVH01016046.1:1000-3000) beyond the length of NEVH01016046.1 size (2208 bp).  Skipping.
Feature (NEVH01016865.1:0-2000) beyond the length of NEVH01016865.1 size (1230 bp).  Skipping.
Feature (NEVH01000475.1:2000-3000) beyond the length of NEVH01000475.1 size (2137 bp).  Skipping.
Feature (NEVH01013662.1:5000-6000) beyond the length of NEVH01013662.1 size (5102 bp).  Skipping.
Feature (NEVH01025213.1:2000-4000) beyond the length of NEVH01025213.1 size (3118 bp).  Skipping.
Feature (NEVH01021920.1:9000-10000) beyond the length of NEVH01021920.1 size (9180 bp).  Skipping.
Feature (NEVH01003086.1:1000-3000) beyond the length of NEVH01003086.1 size (2405 bp).  Skipping.
Feature (NEVH01012713.1:1000-2000) beyond the length of NEVH01012713.1 size (1182 bp).  Skipping.
Feature (NEVH01025657.1:466000-468000) beyond the length of NEVH01025657.1 size (467440 bp).  Skipping.
Feature (NEVH01012655.1:11000-12000) beyond the length of NEVH01012655.1 size (11452 bp).  Skipping.
Feature (NEVH01015437.1:0-2000) beyond the length of NEVH01015437.1 size (1168 bp).  Skipping.
Feature (NEVH01025752.1:0-2000) beyond the length of NEVH01025752.1 size (1968 bp).  Skipping.
Feature (NEVH01027245.1:1000-2000) beyond the length of NEVH01027245.1 size (1502 bp).  Skipping.
Feature (NEVH01020231.1:0-2000) beyond the length of NEVH01020231.1 size (1681 bp).  Skipping.
Feature (NEVH01010667.1:1000-3000) beyond the length of NEVH01010667.1 size (2457 bp).  Skipping.
Feature (NEVH01053512.1:0-2000) beyond the length of NEVH01053512.1 size (1289 bp).  Skipping.
Feature (NEVH01015941.1:24000-25000) beyond the length of NEVH01015941.1 size (24457 bp).  Skipping.
Feature (NEVH01002200.1:1000-2000) beyond the length of NEVH01002200.1 size (1585 bp).  Skipping.
Feature (NEVH01019983.1:70000-72000) beyond the length of NEVH01019983.1 size (71386 bp).  Skipping.
Feature (NEVH01011931.1:247000-248000) beyond the length of NEVH01011931.1 size (247914 bp).  Skipping.
Feature (NEVH01012799.1:0-2000) beyond the length of NEVH01012799.1 size (1548 bp).  Skipping.
Feature (NEVH01014369.1:24000-26000) beyond the length of NEVH01014369.1 size (25674 bp).  Skipping.
Feature (NEVH01024456.1:2000-3000) beyond the length of NEVH01024456.1 size (2536 bp).  Skipping.
Feature (NEVH01010513.1:0-2000) beyond the length of NEVH01010513.1 size (1801 bp).  Skipping.
Feature (NEVH01003102.1:0-2000) beyond the length of NEVH01003102.1 size (1417 bp).  Skipping.
Feature (NEVH01008422.1:1000-2000) beyond the length of NEVH01008422.1 size (1439 bp).  Skipping.
Feature (NEVH01013583.1:313000-315000) beyond the length of NEVH01013583.1 size (314070 bp).  Skipping.
Feature (NEVH01010787.1:0-2000) beyond the length of NEVH01010787.1 size (1091 bp).  Skipping.
Feature (NEVH01022665.1:14000-16000) beyond the length of NEVH01022665.1 size (15909 bp).  Skipping.
Feature (NEVH01013264.1:316000-317000) beyond the length of NEVH01013264.1 size (316854 bp).  Skipping.
Feature (NEVH01002792.1:6000-8000) beyond the length of NEVH01002792.1 size (7570 bp).  Skipping.
Feature (NEVH01000103.1:1000-2000) beyond the length of NEVH01000103.1 size (1161 bp).  Skipping.
Feature (NEVH01022362.1:768000-770000) beyond the length of NEVH01022362.1 size (769376 bp).  Skipping.
Feature (NEVH01026115.1:172000-173000) beyond the length of NEVH01026115.1 size (172679 bp).  Skipping.
Feature (NEVH01026103.1:101000-102000) beyond the length of NEVH01026103.1 size (101617 bp).  Skipping.
Feature (NEVH01021660.1:12000-14000) beyond the length of NEVH01021660.1 size (13988 bp).  Skipping.
Feature (NEVH01018513.1:5000-7000) beyond the length of NEVH01018513.1 size (6840 bp).  Skipping.
Feature (NEVH01009432.1:0-2000) beyond the length of NEVH01009432.1 size (1352 bp).  Skipping.
Feature (NEVH01002915.1:1000-2000) beyond the length of NEVH01002915.1 size (1637 bp).  Skipping.
Feature (NEVH01011986.1:72000-74000) beyond the length of NEVH01011986.1 size (73288 bp).  Skipping.
Feature (NEVH01017889.1:1000-2000) beyond the length of NEVH01017889.1 size (1780 bp).  Skipping.
Feature (NEVH01019416.1:152000-154000) beyond the length of NEVH01019416.1 size (153295 bp).  Skipping.
Feature (NEVH01027412.1:0-2000) beyond the length of NEVH01027412.1 size (1095 bp).  Skipping.
Feature (NEVH01027108.1:157000-159000) beyond the length of NEVH01027108.1 size (158319 bp).  Skipping.
Feature (NEVH01026642.1:1000-2000) beyond the length of NEVH01026642.1 size (1788 bp).  Skipping.
Feature (NEVH01013348.1:2000-4000) beyond the length of NEVH01013348.1 size (3627 bp).  Skipping.
Feature (NEVH01006145.1:1000-2000) beyond the length of NEVH01006145.1 size (1188 bp).  Skipping.
Feature (NEVH01000597.1:1976000-1978000) beyond the length of NEVH01000597.1 size (1977616 bp).  Skipping.
Feature (NEVH01010486.1:380000-381000) beyond the length of NEVH01010486.1 size (380690 bp).  Skipping.
Feature (NEVH01011250.1:0-2000) beyond the length of NEVH01011250.1 size (1294 bp).  Skipping.
Feature (NEVH01008342.1:37000-38000) beyond the length of NEVH01008342.1 size (37469 bp).  Skipping.
Feature (NEVH01020854.1:217000-218000) beyond the length of NEVH01020854.1 size (217245 bp).  Skipping.
Feature (NEVH01008632.1:25000-26000) beyond the length of NEVH01008632.1 size (25954 bp).  Skipping.
Feature (NEVH01015586.1:0-2000) beyond the length of NEVH01015586.1 size (1899 bp).  Skipping.
Feature (NEVH01021208.1:2949000-2951000) beyond the length of NEVH01021208.1 size (2950722 bp).  Skipping.
Feature (NEVH01024105.1:33000-35000) beyond the length of NEVH01024105.1 size (34521 bp).  Skipping.
Feature (NEVH01000640.1:1000-2000) beyond the length of NEVH01000640.1 size (1422 bp).  Skipping.
Feature (NEVH01021051.1:6000-8000) beyond the length of NEVH01021051.1 size (7964 bp).  Skipping.
Feature (NEVH01008497.1:1000-2000) beyond the length of NEVH01008497.1 size (1463 bp).  Skipping.
Feature (NEVH01000069.1:1000-2000) beyond the length of NEVH01000069.1 size (1908 bp).  Skipping.
Feature (NEVH01000295.1:82000-84000) beyond the length of NEVH01000295.1 size (83184 bp).  Skipping.
Feature (NEVH01004428.1:0-2000) beyond the length of NEVH01004428.1 size (1885 bp).  Skipping.
Feature (NEVH01025940.1:1000-2000) beyond the length of NEVH01025940.1 size (1281 bp).  Skipping.
Feature (NEVH01023984.1:513000-515000) beyond the length of NEVH01023984.1 size (514490 bp).  Skipping.
Feature (NEVH01002548.1:944000-946000) beyond the length of NEVH01002548.1 size (945578 bp).  Skipping.
Feature (NEVH01018770.1:1000-2000) beyond the length of NEVH01018770.1 size (1494 bp).  Skipping.
Feature (NEVH01019455.1:0-2000) beyond the length of NEVH01019455.1 size (1098 bp).  Skipping.
Feature (NEVH01016808.1:1000-2000) beyond the length of NEVH01016808.1 size (1282 bp).  Skipping.
Feature (NEVH01026141.1:25000-26000) beyond the length of NEVH01026141.1 size (25390 bp).  Skipping.
Feature (NEVH01000047.1:1000-2000) beyond the length of NEVH01000047.1 size (1834 bp).  Skipping.
Feature (NEVH01024503.1:1000-2000) beyond the length of NEVH01024503.1 size (1600 bp).  Skipping.
Feature (NEVH01019389.1:3000-4000) beyond the length of NEVH01019389.1 size (3340 bp).  Skipping.
Feature (NEVH01011229.1:1000-2000) beyond the length of NEVH01011229.1 size (1685 bp).  Skipping.
Feature (NEVH01018855.1:1000-3000) beyond the length of NEVH01018855.1 size (2270 bp).  Skipping.
Feature (NEVH01003603.1:1000-2000) beyond the length of NEVH01003603.1 size (1502 bp).  Skipping.
Feature (NEVH01001660.1:0-2000) beyond the length of NEVH01001660.1 size (1285 bp).  Skipping.
Feature (NEVH01021923.1:329000-330000) beyond the length of NEVH01021923.1 size (329310 bp).  Skipping.
Feature (NEVH01027807.1:1000-2000) beyond the length of NEVH01027807.1 size (1330 bp).  Skipping.
Feature (NEVH01000946.1:0-2000) beyond the length of NEVH01000946.1 size (1468 bp).  Skipping.
Feature (NEVH01019836.1:2000-4000) beyond the length of NEVH01019836.1 size (3910 bp).  Skipping.
Feature (NEVH01002832.1:0-2000) beyond the length of NEVH01002832.1 size (1857 bp).  Skipping.
Feature (NEVH01023095.1:3000-4000) beyond the length of NEVH01023095.1 size (3671 bp).  Skipping.
Feature (NEVH01019065.1:824000-826000) beyond the length of NEVH01019065.1 size (825425 bp).  Skipping.
Feature (NEVH01025663.1:195000-196000) beyond the length of NEVH01025663.1 size (195405 bp).  Skipping.
Feature (NEVH01002799.1:1000-2000) beyond the length of NEVH01002799.1 size (1247 bp).  Skipping.
Feature (NEVH01054097.1:2000-4000) beyond the length of NEVH01054097.1 size (3823 bp).  Skipping.
Feature (NEVH01009778.1:433000-435000) beyond the length of NEVH01009778.1 size (434283 bp).  Skipping.
Feature (NEVH01005958.1:2000-4000) beyond the length of NEVH01005958.1 size (3292 bp).  Skipping.
Feature (NEVH01011191.1:274000-275000) beyond the length of NEVH01011191.1 size (274409 bp).  Skipping.
Feature (NEVH01013300.1:1000-2000) beyond the length of NEVH01013300.1 size (1511 bp).  Skipping.
Feature (NEVH01013569.1:3000-4000) beyond the length of NEVH01013569.1 size (3033 bp).  Skipping.
Feature (NEVH01025671.1:3000-4000) beyond the length of NEVH01025671.1 size (3569 bp).  Skipping.
Feature (NEVH01005556.1:0-2000) beyond the length of NEVH01005556.1 size (1611 bp).  Skipping.
Feature (NEVH01020934.1:99000-100000) beyond the length of NEVH01020934.1 size (99519 bp).  Skipping.
Feature (NEVH01017641.1:1000-2000) beyond the length of NEVH01017641.1 size (1186 bp).  Skipping.
Feature (NEVH01022670.1:25000-26000) beyond the length of NEVH01022670.1 size (25999 bp).  Skipping.
Feature (NEVH01015996.1:1000-2000) beyond the length of NEVH01015996.1 size (1134 bp).  Skipping.
Feature (NEVH01025142.1:1048000-1049000) beyond the length of NEVH01025142.1 size (1048625 bp).  Skipping.
Feature (NEVH01003601.1:1000-2000) beyond the length of NEVH01003601.1 size (1545 bp).  Skipping.
Feature (NEVH01025204.1:0-2000) beyond the length of NEVH01025204.1 size (1103 bp).  Skipping.
Feature (NEVH01021784.1:2000-3000) beyond the length of NEVH01021784.1 size (2652 bp).  Skipping.
Feature (NEVH01020059.1:0-2000) beyond the length of NEVH01020059.1 size (1569 bp).  Skipping.
Feature (NEVH01008557.1:0-2000) beyond the length of NEVH01008557.1 size (1591 bp).  Skipping.
Feature (NEVH01015198.1:1000-2000) beyond the length of NEVH01015198.1 size (1479 bp).  Skipping.
Feature (NEVH01011200.1:33000-35000) beyond the length of NEVH01011200.1 size (34456 bp).  Skipping.
Feature (NEVH01005484.1:2000-3000) beyond the length of NEVH01005484.1 size (2509 bp).  Skipping.
Feature (NEVH01000603.1:232000-234000) beyond the length of NEVH01000603.1 size (233676 bp).  Skipping.
Feature (NEVH01009424.1:278000-280000) beyond the length of NEVH01009424.1 size (279473 bp).  Skipping.
Feature (NEVH01005958.1:3000-4000) beyond the length of NEVH01005958.1 size (3292 bp).  Skipping.
Feature (NEVH01016021.1:0-2000) beyond the length of NEVH01016021.1 size (1976 bp).  Skipping.
Feature (NEVH01008207.1:794000-796000) beyond the length of NEVH01008207.1 size (795683 bp).  Skipping.
Feature (NEVH01027202.1:0-2000) beyond the length of NEVH01027202.1 size (1170 bp).  Skipping.
Feature (NEVH01002662.1:2000-3000) beyond the length of NEVH01002662.1 size (2708 bp).  Skipping.
Feature (NEVH01022655.1:23000-25000) beyond the length of NEVH01022655.1 size (24744 bp).  Skipping.

In [198]:
%%bash

db=../data/Csec.fa
bed=../data/20231204_Csec_5fold_peaks_4kss.bed
out=../data/20231204_Csec_hs_5fold_4kss.fa

bedtools getfasta -fi $db -bed $bed -fo $out


db=../data/Csec.fa
bed=../data/20231205_Csec_5fold_nopeaks_4kss.bed
out=../data/20231204_Csec_hs_5fold_background_4kss.fa

bedtools getfasta -fi $db -bed $bed -fo $out

Feature (NEVH01018006.1:3000-4000) beyond the length of NEVH01018006.1 size (3609 bp).  Skipping.
Feature (NEVH01000595.1:2118000-2119000) beyond the length of NEVH01000595.1 size (2118713 bp).  Skipping.
Feature (NEVH01010480.1:2306000-2307000) beyond the length of NEVH01010480.1 size (2306319 bp).  Skipping.
Feature (NEVH01017307.1:1000-2000) beyond the length of NEVH01017307.1 size (1319 bp).  Skipping.
Feature (NEVH01014373.1:254000-256000) beyond the length of NEVH01014373.1 size (255944 bp).  Skipping.
Feature (NEVH01004982.1:58000-59000) beyond the length of NEVH01004982.1 size (58611 bp).  Skipping.
Feature (NEVH01014373.1:255000-256000) beyond the length of NEVH01014373.1 size (255944 bp).  Skipping.
Feature (NEVH01009081.1:266000-268000) beyond the length of NEVH01009081.1 size (267562 bp).  Skipping.
Feature (NEVH01013552.1:1655000-1657000) beyond the length of NEVH01013552.1 size (1656948 bp).  Skipping.
Feature (NEVH01009081.1:267000-268000) beyond the length of NEVH01009081.1 size (267562 bp).  Skipping.
Feature (NEVH01013285.1:15000-16000) beyond the length of NEVH01013285.1 size (15514 bp).  Skipping.
Feature (NEVH01008784.1:1000-2000) beyond the length of NEVH01008784.1 size (1635 bp).  Skipping.
Feature (NEVH01013552.1:1656000-1657000) beyond the length of NEVH01013552.1 size (1656948 bp).  Skipping.
Feature (NEVH01005899.1:498000-499000) beyond the length of NEVH01005899.1 size (498617 bp).  Skipping.
Feature (NEVH01004431.1:87000-89000) beyond the length of NEVH01004431.1 size (88340 bp).  Skipping.
Feature (NEVH01000250.1:2236000-2237000) beyond the length of NEVH01000250.1 size (2236795 bp).  Skipping.
Feature (NEVH01000596.1:774000-775000) beyond the length of NEVH01000596.1 size (774875 bp).  Skipping.
Feature (NEVH01013833.1:0-2000) beyond the length of NEVH01013833.1 size (1489 bp).  Skipping.
Feature (NEVH01007936.1:12000-13000) beyond the length of NEVH01007936.1 size (12925 bp).  Skipping.
Feature (NEVH01013328.1:40000-42000) beyond the length of NEVH01013328.1 size (41703 bp).  Skipping.
Feature (NEVH01027166.1:9000-11000) beyond the length of NEVH01027166.1 size (10225 bp).  Skipping.
Feature (NEVH01012681.1:0-2000) beyond the length of NEVH01012681.1 size (1870 bp).  Skipping.
Feature (NEVH01018903.1:1000-2000) beyond the length of NEVH01018903.1 size (1857 bp).  Skipping.
Feature (NEVH01026303.1:1000-2000) beyond the length of NEVH01026303.1 size (1245 bp).  Skipping.
Feature (NEVH01005525.1:0-2000) beyond the length of NEVH01005525.1 size (1531 bp).  Skipping.
Feature (NEVH01017392.1:1000-2000) beyond the length of NEVH01017392.1 size (1552 bp).  Skipping.
Feature (NEVH01003139.1:13000-14000) beyond the length of NEVH01003139.1 size (13469 bp).  Skipping.
Feature (NEVH01003534.1:0-2000) beyond the length of NEVH01003534.1 size (1245 bp).  Skipping.
Feature (NEVH01002172.1:1000-2000) beyond the length of NEVH01002172.1 size (1097 bp).  Skipping.
Feature (NEVH01013646.1:12000-13000) beyond the length of NEVH01013646.1 size (12250 bp).  Skipping.
Feature (NEVH01000062.1:1000-2000) beyond the length of NEVH01000062.1 size (1765 bp).  Skipping.
Feature (NEVH01010532.1:35000-36000) beyond the length of NEVH01010532.1 size (35447 bp).  Skipping.
Feature (NEVH01006589.1:37000-39000) beyond the length of NEVH01006589.1 size (38080 bp).  Skipping.
Feature (NEVH01009511.1:1000-2000) beyond the length of NEVH01009511.1 size (1296 bp).  Skipping.
Feature (NEVH01008058.1:0-2000) beyond the length of NEVH01008058.1 size (1347 bp).  Skipping.
Feature (NEVH01025121.1:1000-2000) beyond the length of NEVH01025121.1 size (1471 bp).  Skipping.
Feature (NEVH01017733.1:0-2000) beyond the length of NEVH01017733.1 size (1747 bp).  Skipping.
Feature (NEVH01001337.1:2892000-2893000) beyond the length of NEVH01001337.1 size (2892088 bp).  Skipping.
Feature (NEVH01013320.1:35000-36000) beyond the length of NEVH01013320.1 size (35254 bp).  Skipping.
Feature (NEVH01015433.1:2000-3000) beyond the length of NEVH01015433.1 size (2574 bp).  Skipping.
Feature (NEVH01019079.1:0-2000) beyond the length of NEVH01019079.1 size (1621 bp).  Skipping.
Feature (NEVH01020916.1:1000-2000) beyond the length of NEVH01020916.1 size (1568 bp).  Skipping.
Feature (NEVH01025118.1:0-2000) beyond the length of NEVH01025118.1 size (1930 bp).  Skipping.
Feature (NEVH01027244.1:1000-3000) beyond the length of NEVH01027244.1 size (2291 bp).  Skipping.
Feature (NEVH01014059.1:1000-2000) beyond the length of NEVH01014059.1 size (1956 bp).  Skipping.
Feature (NEVH01026389.1:360000-362000) beyond the length of NEVH01026389.1 size (361439 bp).  Skipping.

In [217]:
seqs = pd.read_csv("../data/streme_out_v2/sequences.tsv", sep='\t')
seqs = seqs.dropna(subset='motif_ALT_ID')
seqs['idnum'] = [ int(i.split('-')[1]) for i in seqs.motif_ALT_ID]
seqs.loc[seqs.idnum<13][['motif_ID', 'motif_P-value']].drop_duplicates()